"""Build embedded per-character thumb references from local PMX skeletons.

Identity uses known source hashes, or a model key confirmed by texture names.
Output contains normalized bone directions only, never meshes or local paths.
"""
import argparse
import json
import re
from pathlib import Path

import numpy as np
from compile_character_faces import read_pmx, normalize


def unit(v):
    n = float(np.linalg.norm(v))
    if not np.isfinite(n) or n < 1e-6:
        raise ValueError('Degenerate thumb reference')
    return np.asarray(v) / n


def derive(model):
    bones = model['bones']
    names = {}
    for i, b in enumerate(bones):
        names.setdefault(normalize(b['name']), []).append(i)

    def find(name):
        found = names.get(name, [])
        if len(found) != 1:
            raise ValueError('Missing or ambiguous bone: ' + name)
        return found[0]

    def pos(i):
        return np.array(bones[i]['rest'])

    sides = []
    for side in ('左', '右'):
        wrist, middle, index, little = [find(side + n) for n in ('手首', '中指1', '人指1', '小指1')]
        forward = unit(pos(middle) - pos(wrist))
        across = pos(index) - pos(little)
        across = unit(across - forward * np.dot(across, forward))
        frame = np.column_stack((forward, across, np.cross(forward, across)))
        scale = float(np.linalg.norm(pos(middle) - pos(wrist)))
        joints = [find(side + '親指' + str(j)) for j in range(3)]
        for j, i in enumerate(joints):
            if bones[i]['parent'] != (joints[j - 1] if j else wrist):
                raise ValueError('Unsupported thumb hierarchy')
        last = bones[joints[-1]]
        if last['flags'] & 1:
            tip = last['tail']
            if not (0 <= tip < len(bones)) or bones[tip]['parent'] != joints[-1]:
                raise ValueError('Invalid thumb tip bone')
            end = pos(tip)
        else:
            end = pos(joints[-1]) + np.array(last['tail'])
        points = [pos(i) for i in joints] + [end]
        lengths = [float(np.linalg.norm(points[j + 1] - points[j])) / scale for j in range(3)]
        directions = [frame.T @ unit(points[j + 1] - points[j]) if j < 2 or lengths[j] > 1e-6
                      else np.zeros(3) for j in range(3)]
        if lengths[2] <= 1e-6:
            lengths[2] = 0.0  # Explicitly unavailable terminal direction; retain native last-joint rotation.
        root = frame.T @ (points[0] - pos(wrist)) / scale
        if not np.all(np.isfinite(root)) or np.linalg.norm(root) > 2 or any(v < .03 or v > 2 for v in lengths[:2]) or lengths[2] > 2:
            raise ValueError('Unusable normalized thumb dimensions')
        sides.append(dict(root=root.tolist(), directions=[d.tolist() for d in directions], lengths=lengths,
                          palm_forward=forward.tolist(), palm_across=across.tolist()))
    return sides


def number(v):
    return f'{float(v):.8f}f'


def vector(v):
    return '{' + ','.join(number(f) for f in v) + '}'


def identify(model, profiles, label):
    known = profiles.get(model['hash'])
    if known:
        return known
    # Some models cannot produce facial profiles, but still have valid hands.
    # Confirm their model key with multiple named texture groups; never infer
    # identity from a folder name or reuse another character's measurements.
    key = model['name'].lower()
    if not re.fullmatch(r'[a-z0-9_]{1,64}', key):
        return None
    pattern = r'(?:^|/)(?:t_actor_)?' + re.escape(key) + r'_(face|cloth|body|hair|eye)(?:_|\.)'
    groups = set()
    for texture in model.get('textures', []):
        match = re.search(pattern, texture.replace('\\', '/').lower())
        if match:
            groups.add(match[1])
    return dict(model=key, label=label, source_hash=model['hash']) if len(groups) >= 2 else None


def emit(records):
    lines = ['#pragma once', '// Generated by tools/compile_character_thumbs.py; no model files required at runtime.',
             'namespace mmd {', 'inline const ThumbReference CharacterThumbReferences[] = {']
    for row in sorted(records, key=lambda r: r['model']):
        text = lambda s: 'u8' + json.dumps(s, ensure_ascii=False)
        hands = []
        for h in row['hands']:
            hands.append('{' + vector(h['root']) + ',{' + ','.join(vector(v) for v in h['directions']) + '},' +
                         vector(h['lengths']) + ',' + vector(h['palm_forward']) + ',' + vector(h['palm_across']) + '}')
        lines.append('  {' + ','.join(text(row[k]) for k in ('model', 'label', 'source_hash')) + ',{' + ','.join(hands) + '}},')
    lines += ['};', '} // namespace mmd', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('models', type=Path)
    parser.add_argument('--profiles', type=Path, default=Path('resources/character-faces'))
    parser.add_argument('--output', type=Path, default=Path('resources/character-thumbs/builtin.h'))
    parser.add_argument('--report', type=Path)
    args = parser.parse_args()
    profiles = {}
    for path in sorted(args.profiles.glob('*.face.json')):
        p = json.loads(path.read_text(encoding='utf-8-sig'))
        profiles[p['source_hash']] = p
    records, seen, issues, unidentified = [], set(), [], []
    for path in sorted(args.models.rglob('*.pmx')):
        model = read_pmx(path)
        p = identify(model, profiles, path.stem)
        if not p:
            unidentified.append(model['name'])
            continue
        if model['hash'] in seen:
            continue
        seen.add(model['hash'])
        try:
            records.append(dict(model=p['model'], label=p['label'], source_hash=model['hash'], hands=derive(model)))
        except ValueError as e:
            issues.append(dict(model=p['model'], reason=str(e)))
    unique, ambiguous = {}, set()
    for row in records:
        old = unique.get(row['model'])
        if old:
            flatten = lambda r: np.concatenate([np.ravel(h[k]) for h in r['hands'] for k in ('root', 'directions', 'lengths', 'palm_forward', 'palm_across')])
            if not np.allclose(flatten(old), flatten(row), rtol=.01, atol=.005):
                ambiguous.add(row['model'])
        else:
            unique[row['model']] = row
    for key in ambiguous:
        unique.pop(key)
        issues.append(dict(model=key, reason='Different thumb geometry across character variants'))
    records = list(unique.values())
    if not records:
        raise ValueError('No usable references')
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(emit(records), encoding='utf-8')
    report = dict(count=len(records), profiles=records, rejected=issues,
                  unidentified=unidentified,
                  partial=[p['model'] for p in records if any(h['lengths'][2] == 0 for h in p['hands'])],
                  unavailable=[p['model'] for h, p in profiles.items() if h not in seen])
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
    print(f'Compiled {len(records)} character thumb references; rejected {len(issues)}; unavailable {len(report["unavailable"])}')


if __name__ == '__main__':
    main()
